Fix storing changes in WikiPage for Python3
WikiPage.store() method should call str.encode() after replacing newline characters. Otherwise, under Python 3 it will fail with

TypeError: 'str' does not support the buffer interface